platform:
  security:
    accounts:
      auto-locking:
        bad-credentials:
          max-consecutive: 3
          expiry-time: 30
    cors-config:
      allowedHeaders: "*"
      allowedOrigins: "http://localhost:3000"
      allowedMethods: "*"
      path-mappings: "/**"
    login:
      successUrl: "http://localhost:3000"
      failureUrl: "http://localhost:3000"
    jwt-issuer: "platform-backend"