platform-security:
  allowed-paths: >
    /customers/v1/create/**,
    /auth/v1/unlock-account/**
  unlock-complete-url: "http://localhost:3000/accounts/unlock?code=%s"
  unlock-reply-email: "admin@platform.com"
  max-consecutive-bad-credentials: 3
  bad-credentials-expiry-time: 300
  cors-allowed-headers: "*"
  cors-allowed-origins: "*"
  cors-allowed-methods: "*"
  cors-path-mappings: "/**"
  login-success-url: "http://localhost:3000"
  login-failure-url: "http://localhost:3000"
  jwt-issuer: "platform"
