platform:
  security:
    allowed-paths: >
      /customers/v1/person/register,
      /auth/v1/unlock-account/**
    accounts:
      auto-unlocking:
        addresses:
          complete: "http://localhost:3000/accounts/unlock?code=%s"
          reply: "admin@platform.com"
      auto-locking:
        bad-credentials:
          max-consecutive: 3
          expiry-time: 300
    cors-config:
      allowedHeaders: "*"
      allowedOrigins: "*"
      allowedMethods: "*"
      path-mappings: "/**"
    login:
      successUrl: "http://localhost:3000"
      failureUrl: "http://localhost:3000"
    jwt-issuer: "platform"
