version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DB
    ports:
      - "5432:5432"

  platform-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/$POSTGRES_USER
      spring.datasource.username: $POSTGRES_USER
      spring.datasource.password: $POSTGRES_PASSWORD