server:
  port: 8081
spring:
  application:
    name: authorization-server
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${dbUrl:jdbc:postgresql://localhost:5432/authserver}
    username: ${dbuser:authserver}
    password: ${dbpass:authserverisnice}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    open-in-view: false

