spring:
  mail:
    host: "smtp.gmail.com"
    password: "<your-password>"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: "<your-username>"