spring:
  profiles:
    include:
      - security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${dbUrl:jdbc:postgresql://localhost:5432/authserver}
    username: ${dbuser:authserver}
    password: ${dbpass:authserverisnice}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE


