spring:
  profiles:
    include:
      - security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${dbUrl:jdbc:postgresql://localhost:5432/authserver}
    username: ${dbuser:authserver}
    password: ${dbpass:authserverisnice}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

platform:
  security:
    cors-config:
      allowedHeaders: "*"
      allowedOrigins: "http://localhost:3000"
      allowedMethods: "*"
      path-mappings: "/**"
    login:
      successUrl: "http://localhost:3000"
      failureUrl: "http://localhost:3000"
    jwt-issuer: "ticket-platform"