package com.platform.model;

public enum AuthenticationStatusReason {
  BAD_CREDENTIALS,
  ACCOUNT_EXPIRED,
  ACCOUNT_LOCKED,
  SUCCESSFUL_AUTHENTICATION,
  HACKED,
  RULE_VIOLATION,
  CLIENT_OPERATION,
  UNKNOWN,
}
