package com.platform.model;

public enum AuthenticationStatusReason {
  BAD_CREDENTIALS,
  ACCOUNT_EXPIRED,
  ACCOUNT_LOCKED,
  UNKNOWN, ACCOUNT_DISABLED,
  SUCCESSFUL_AUTHENTICATION,
  ACCOUNT_HACKED,
}
